apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2   # 파드 갯수
  selector:
    matchLabels:
      app: nginx-web-label    # Deployment가 관리할 파드명
  template:
    metadata:
      labels:
        app: nginx-web-label
    spec:
      containers:
        - name: nginx-container
<<<<<<< HEAD
          image: hyeon22/nginx:598ecc2e311de0874f59838cf1189af12043fc2b
=======
          image: hyeon22/nginx:b338875ab0f7f0fd0b9752e42eeb433900946ef2
>>>>>>> f9fefb4 (eks)
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
          