# 워크플로우(작업) 이름
name: GitOps ArgoCD CICD Pipeline
on:
  push:
    branches:
      - main  # 트리거 설정: main 브랜치에 푸시될 때 실행

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # runs-on에 정의된 서버가 git에 업로드된 파일을 수정할 수 있도록함
    steps:              # (deployment의 이미지 버전명 수정)
      - name: 소스코드 체크아웃   # git에 push된 파일을 서버로 복사
        uses: actions/checkout@v4

      - name: Docker Hub 로그인 # ex4 참고
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .  # git의 root
          file: ./nginx/Dockerfile  # Dockerfile의 경로 및 파일명
          push: true
          tags: hyeon22/nginx:${{ github.sha }} # (중요) 이미지명 정의(태그 자동생성)
                                                # 이미지명이 중복되지 않게 만들어주는 난수발생기
      - name: 쿠버네티스 파일의 이미지 태그 갱신 및 Git push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # k8s/deployment.yaml 파일 내의 이미지 태그를 현재 커밋 SHA 버전으로 변경
          # (사용하시는 deployment.yaml 파일의 경로에맞게 수정해주세요)
          sed -i 's|image: hyeon22/nginx:.*|image: hyeon22/nginx:${{ github.sha }}|g" ./k8s/deployment.yaml
          
          git add ./k8s/deployment.yaml
          git commit -m "Deployment file tag Update(${{ github.sha }})"
          git push